<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\RecipeIngredient;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            // Завтраки
            [
                'title' => 'Овсянка с ягодами и орехами',
                'slug' => 'ovsyanka-s-yagodami',
                'description' => 'Питательный завтрак с овсяными хлопьями, свежими ягодами и грецкими орехами.',
                'instructions' => "1. Залейте овсяные хлопья водой или молоком.\n2. Варите на среднем огне 5-7 минут.\n3. Добавьте ягоды и орехи.\n4. По желанию добавьте мёд.",
                'prep_time' => 5,
                'cook_time' => 7,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 350,
                'proteins' => 12,
                'fats' => 14,
                'carbs' => 45,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'high-fiber'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Овсяные хлопья', 'amount' => 60, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Молоко 2.5%', 'amount' => 150, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Ягоды (малина, черника)', 'amount' => 50, 'unit' => 'г', 'category' => 'Фрукты'],
                    ['name' => 'Грецкие орехи', 'amount' => 20, 'unit' => 'г', 'category' => 'Орехи'],
                    ['name' => 'Мёд', 'amount' => 10, 'unit' => 'г', 'category' => 'Прочее', 'is_optional' => true],
                ],
            ],
            [
                'title' => 'Омлет с овощами',
                'slug' => 'omlet-s-ovoshchami',
                'description' => 'Пышный омлет с помидорами, болгарским перцем и зеленью.',
                'instructions' => "1. Взбейте яйца с молоком.\n2. Нарежьте овощи кубиками.\n3. Обжарьте овощи на сковороде 2-3 минуты.\n4. Залейте яичной смесью.\n5. Готовьте под крышкой 5-7 минут.",
                'prep_time' => 10,
                'cook_time' => 10,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 280,
                'proteins' => 18,
                'fats' => 20,
                'carbs' => 8,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'low-carb', 'high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Яйца куриные', 'amount' => 2, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Молоко 2.5%', 'amount' => 50, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Помидор', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Болгарский перец', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Зелень (укроп, петрушка)', 'amount' => 10, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Масло оливковое', 'amount' => 5, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],
            [
                'title' => 'Творог с фруктами',
                'slug' => 'tvorog-s-fruktami',
                'description' => 'Нежный творог с бананом, яблоком и корицей.',
                'instructions' => "1. Выложите творог в миску.\n2. Нарежьте фрукты.\n3. Добавьте фрукты к творогу.\n4. Посыпьте корицей.",
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 320,
                'proteins' => 25,
                'fats' => 8,
                'carbs' => 38,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Творог 5%', 'amount' => 150, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Банан', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Яблоко', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Корица', 'amount' => 2, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],
            [
                'title' => 'Гречневая каша с молоком',
                'slug' => 'grechnevaya-kasha',
                'description' => 'Классическая гречневая каша на молоке с маслом.',
                'instructions' => "1. Промойте гречку.\n2. Залейте водой и варите 15 минут.\n3. Добавьте молоко и масло.\n4. Доведите до готовности.",
                'prep_time' => 5,
                'cook_time' => 20,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 340,
                'proteins' => 14,
                'fats' => 10,
                'carbs' => 50,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'gluten-free'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Гречневая крупа', 'amount' => 80, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Молоко 2.5%', 'amount' => 100, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Масло сливочное', 'amount' => 10, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Соль', 'amount' => 2, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],
            [
                'title' => 'Яичница с авокадо на тосте',
                'slug' => 'yaichnitsa-s-avokado',
                'description' => 'Тост из цельнозернового хлеба с авокадо и яйцом пашот.',
                'instructions' => "1. Поджарьте хлеб в тостере.\n2. Разомните авокадо вилкой.\n3. Приготовьте яйцо пашот.\n4. Выложите авокадо на тост, сверху яйцо.",
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 1,
                'difficulty' => 'medium',
                'calories' => 380,
                'proteins' => 15,
                'fats' => 25,
                'carbs' => 28,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'high-fat'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Хлеб цельнозерновой', 'amount' => 1, 'unit' => 'ломтик', 'category' => 'Хлеб'],
                    ['name' => 'Авокадо', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Яйцо куриное', 'amount' => 1, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Соль, перец', 'amount' => 2, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],

            // Обеды
            [
                'title' => 'Куриная грудка с киноа и овощами',
                'slug' => 'kurinaya-grudka-s-kinoa',
                'description' => 'Запечённая куриная грудка с гарниром из киноа и свежих овощей.',
                'instructions' => "1. Замаринуйте курицу в специях.\n2. Запекайте в духовке 25 минут при 180°C.\n3. Отварите киноа по инструкции.\n4. Нарежьте овощи.\n5. Подавайте вместе.",
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 1,
                'difficulty' => 'medium',
                'calories' => 420,
                'proteins' => 38,
                'fats' => 12,
                'carbs' => 40,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein', 'gluten-free'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Куриная грудка', 'amount' => 150, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Киноа', 'amount' => 60, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Огурец', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Помидор', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Масло оливковое', 'amount' => 10, 'unit' => 'мл', 'category' => 'Масла'],
                    ['name' => 'Специи (паприка, чеснок)', 'amount' => 5, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],
            [
                'title' => 'Суп-пюре из брокколи',
                'slug' => 'sup-pyure-iz-brokkoli',
                'description' => 'Нежный крем-суп из брокколи со сливками.',
                'instructions' => "1. Отварите брокколи в бульоне 15 минут.\n2. Измельчите блендером.\n3. Добавьте сливки.\n4. Подавайте с сухариками.",
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'easy',
                'calories' => 180,
                'proteins' => 8,
                'fats' => 10,
                'carbs' => 15,
                'category' => 'lunch',
                'dietary_tags' => ['vegetarian', 'low-calorie'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Брокколи', 'amount' => 300, 'unit' => 'г', 'category' => 'Овощи'],
                    ['name' => 'Сливки 10%', 'amount' => 100, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Лук репчатый', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Бульон овощной', 'amount' => 500, 'unit' => 'мл', 'category' => 'Прочее'],
                    ['name' => 'Соль, перец', 'amount' => 3, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],
            [
                'title' => 'Салат с тунцом и яйцом',
                'slug' => 'salat-s-tuntsom',
                'description' => 'Белковый салат с консервированным тунцом, яйцом и овощами.',
                'instructions' => "1. Отварите яйца.\n2. Нарежьте овощи.\n3. Смешайте все ингредиенты.\n4. Заправьте оливковым маслом.",
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 350,
                'proteins' => 32,
                'fats' => 20,
                'carbs' => 12,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein', 'low-carb'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Тунец консервированный', 'amount' => 100, 'unit' => 'г', 'category' => 'Рыба'],
                    ['name' => 'Яйца куриные', 'amount' => 2, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Огурец', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Листья салата', 'amount' => 50, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Масло оливковое', 'amount' => 15, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],
            [
                'title' => 'Гречка с говядиной и грибами',
                'slug' => 'grechka-s-govyadinoy',
                'description' => 'Сытное блюдо из гречки с тушёной говядиной и шампиньонами.',
                'instructions' => "1. Нарежьте говядину кубиками.\n2. Обжарьте мясо до золотистой корочки.\n3. Добавьте грибы и лук.\n4. Тушите 30 минут.\n5. Подавайте с отварной гречкой.",
                'prep_time' => 15,
                'cook_time' => 40,
                'servings' => 2,
                'difficulty' => 'medium',
                'calories' => 450,
                'proteins' => 35,
                'fats' => 18,
                'carbs' => 42,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein', 'gluten-free'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Говядина', 'amount' => 200, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Гречневая крупа', 'amount' => 100, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Шампиньоны', 'amount' => 150, 'unit' => 'г', 'category' => 'Овощи'],
                    ['name' => 'Лук репчатый', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Масло растительное', 'amount' => 15, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],
            [
                'title' => 'Паста с курицей и шпинатом',
                'slug' => 'pasta-s-kuritsey',
                'description' => 'Паста из твёрдых сортов пшеницы с куриным филе в сливочном соусе.',
                'instructions' => "1. Отварите пасту.\n2. Обжарьте курицу.\n3. Добавьте шпинат и сливки.\n4. Смешайте с пастой.",
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 480,
                'proteins' => 32,
                'fats' => 18,
                'carbs' => 52,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Паста (пенне)', 'amount' => 80, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Куриное филе', 'amount' => 120, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Шпинат', 'amount' => 50, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Сливки 20%', 'amount' => 50, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Чеснок', 'amount' => 2, 'unit' => 'зубчика', 'category' => 'Овощи'],
                ],
            ],

            // Ужины
            [
                'title' => 'Лосось на пару с овощами',
                'slug' => 'losos-na-paru',
                'description' => 'Нежный лосось, приготовленный на пару, с гарниром из овощей.',
                'instructions' => "1. Посолите и поперчите лосось.\n2. Готовьте на пару 15 минут.\n3. Отварите овощи на пару.\n4. Подавайте с лимоном.",
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 360,
                'proteins' => 35,
                'fats' => 22,
                'carbs' => 8,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein', 'low-carb', 'omega-3'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Лосось (филе)', 'amount' => 150, 'unit' => 'г', 'category' => 'Рыба'],
                    ['name' => 'Брокколи', 'amount' => 100, 'unit' => 'г', 'category' => 'Овощи'],
                    ['name' => 'Морковь', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Лимон', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Соль, перец', 'amount' => 3, 'unit' => 'г', 'category' => 'Специи'],
                ],
            ],
            [
                'title' => 'Куриные котлеты с овощным салатом',
                'slug' => 'kurinye-kotlety',
                'description' => 'Диетические куриные котлеты на пару с лёгким салатом.',
                'instructions' => "1. Измельчите куриное филе.\n2. Добавьте яйцо и специи.\n3. Сформируйте котлеты.\n4. Готовьте на пару 20 минут.\n5. Подавайте с салатом.",
                'prep_time' => 20,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'medium',
                'calories' => 320,
                'proteins' => 35,
                'fats' => 12,
                'carbs' => 15,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein', 'low-fat'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Куриное филе', 'amount' => 300, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Яйцо куриное', 'amount' => 1, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Лук репчатый', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Огурец', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Помидор', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Зелень', 'amount' => 20, 'unit' => 'г', 'category' => 'Зелень'],
                ],
            ],
            [
                'title' => 'Запечённая треска с лимоном',
                'slug' => 'zapechennaya-treska',
                'description' => 'Нежная треска, запечённая в духовке с лимоном и травами.',
                'instructions' => "1. Выложите рыбу на фольгу.\n2. Посолите, поперчите, добавьте лимон.\n3. Заверните в фольгу.\n4. Запекайте 20 минут при 180°C.",
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 280,
                'proteins' => 32,
                'fats' => 8,
                'carbs' => 5,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein', 'low-carb', 'low-fat'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Треска (филе)', 'amount' => 180, 'unit' => 'г', 'category' => 'Рыба'],
                    ['name' => 'Лимон', 'amount' => 0.5, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Чеснок', 'amount' => 2, 'unit' => 'зубчика', 'category' => 'Овощи'],
                    ['name' => 'Укроп', 'amount' => 10, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Масло оливковое', 'amount' => 10, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],
            [
                'title' => 'Овощное рагу с индейкой',
                'slug' => 'ovoshchnoe-ragu',
                'description' => 'Тушёные овощи с нежным филе индейки.',
                'instructions' => "1. Нарежьте индейку и овощи.\n2. Обжарьте индейку.\n3. Добавьте овощи.\n4. Тушите 25 минут под крышкой.",
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 2,
                'difficulty' => 'medium',
                'calories' => 340,
                'proteins' => 30,
                'fats' => 12,
                'carbs' => 28,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein', 'low-fat'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Филе индейки', 'amount' => 200, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Кабачок', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Баклажан', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Помидоры', 'amount' => 2, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Лук репчатый', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Чеснок', 'amount' => 3, 'unit' => 'зубчика', 'category' => 'Овощи'],
                ],
            ],
            [
                'title' => 'Греческий салат с курицей',
                'slug' => 'grecheskiy-salat-s-kuritsey',
                'description' => 'Классический греческий салат с добавлением куриной грудки.',
                'instructions' => "1. Отварите или запеките курицу.\n2. Нарежьте овощи кубиками.\n3. Добавьте сыр фета.\n4. Заправьте оливковым маслом.",
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 380,
                'proteins' => 32,
                'fats' => 24,
                'carbs' => 12,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein', 'low-carb'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Куриная грудка', 'amount' => 120, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Огурец', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Помидор', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Сыр фета', 'amount' => 50, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Маслины', 'amount' => 30, 'unit' => 'г', 'category' => 'Овощи'],
                    ['name' => 'Масло оливковое', 'amount' => 15, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],

            // Перекусы
            [
                'title' => 'Греческий йогурт с мёдом',
                'slug' => 'grecheskiy-yogurt',
                'description' => 'Натуральный греческий йогурт с мёдом и орехами.',
                'instructions' => "1. Выложите йогурт в миску.\n2. Добавьте мёд.\n3. Посыпьте орехами.",
                'prep_time' => 2,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 180,
                'proteins' => 12,
                'fats' => 8,
                'carbs' => 18,
                'category' => 'snack',
                'dietary_tags' => ['vegetarian', 'high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Йогурт греческий', 'amount' => 150, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Мёд', 'amount' => 15, 'unit' => 'г', 'category' => 'Прочее'],
                    ['name' => 'Миндаль', 'amount' => 15, 'unit' => 'г', 'category' => 'Орехи'],
                ],
            ],
            [
                'title' => 'Яблоко с арахисовой пастой',
                'slug' => 'yabloko-s-arahisovoy-pastoy',
                'description' => 'Свежее яблоко с натуральной арахисовой пастой.',
                'instructions' => "1. Нарежьте яблоко дольками.\n2. Подавайте с арахисовой пастой для макания.",
                'prep_time' => 3,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 200,
                'proteins' => 6,
                'fats' => 12,
                'carbs' => 22,
                'category' => 'snack',
                'dietary_tags' => ['vegetarian', 'vegan'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Яблоко', 'amount' => 1, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Арахисовая паста', 'amount' => 20, 'unit' => 'г', 'category' => 'Орехи'],
                ],
            ],
            [
                'title' => 'Морковные палочки с хумусом',
                'slug' => 'morkovnye-palochki-s-humusom',
                'description' => 'Свежая морковь с домашним хумусом.',
                'instructions' => "1. Нарежьте морковь палочками.\n2. Подавайте с хумусом.",
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 150,
                'proteins' => 5,
                'fats' => 8,
                'carbs' => 16,
                'category' => 'snack',
                'dietary_tags' => ['vegetarian', 'vegan', 'high-fiber'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Морковь', 'amount' => 2, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Хумус', 'amount' => 50, 'unit' => 'г', 'category' => 'Прочее'],
                ],
            ],
            [
                'title' => 'Банан с творогом',
                'slug' => 'banan-s-tvorogom',
                'description' => 'Быстрый перекус из банана и творога.',
                'instructions' => "1. Нарежьте банан.\n2. Смешайте с творогом.",
                'prep_time' => 3,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 220,
                'proteins' => 15,
                'fats' => 5,
                'carbs' => 32,
                'category' => 'snack',
                'dietary_tags' => ['vegetarian', 'high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Банан', 'amount' => 1, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Творог 5%', 'amount' => 100, 'unit' => 'г', 'category' => 'Молочные'],
                ],
            ],
            [
                'title' => 'Горсть орехов и сухофруктов',
                'slug' => 'orehi-i-suhofrukty',
                'description' => 'Энергетический микс из орехов и сухофруктов.',
                'instructions' => "1. Смешайте орехи и сухофрукты.\n2. Порция — одна горсть.",
                'prep_time' => 1,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 180,
                'proteins' => 5,
                'fats' => 12,
                'carbs' => 15,
                'category' => 'snack',
                'dietary_tags' => ['vegetarian', 'vegan', 'high-energy'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Миндаль', 'amount' => 15, 'unit' => 'г', 'category' => 'Орехи'],
                    ['name' => 'Грецкие орехи', 'amount' => 10, 'unit' => 'г', 'category' => 'Орехи'],
                    ['name' => 'Курага', 'amount' => 15, 'unit' => 'г', 'category' => 'Сухофрукты'],
                    ['name' => 'Изюм', 'amount' => 10, 'unit' => 'г', 'category' => 'Сухофрукты'],
                ],
            ],

            // Дополнительные рецепты
            [
                'title' => 'Рис с овощами и креветками',
                'slug' => 'ris-s-krevetkami',
                'description' => 'Ароматный рис с креветками и овощами в азиатском стиле.',
                'instructions' => "1. Отварите рис.\n2. Обжарьте креветки с чесноком.\n3. Добавьте овощи.\n4. Смешайте с рисом и соевым соусом.",
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 1,
                'difficulty' => 'medium',
                'calories' => 400,
                'proteins' => 28,
                'fats' => 10,
                'carbs' => 52,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein', 'low-fat'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Рис басмати', 'amount' => 80, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Креветки', 'amount' => 150, 'unit' => 'г', 'category' => 'Морепродукты'],
                    ['name' => 'Болгарский перец', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Горошек зелёный', 'amount' => 50, 'unit' => 'г', 'category' => 'Овощи'],
                    ['name' => 'Соевый соус', 'amount' => 15, 'unit' => 'мл', 'category' => 'Соусы'],
                    ['name' => 'Чеснок', 'amount' => 2, 'unit' => 'зубчика', 'category' => 'Овощи'],
                ],
            ],
            [
                'title' => 'Смузи с бананом и шпинатом',
                'slug' => 'smuzi-so-shpinatom',
                'description' => 'Зелёный смузи для бодрости и энергии.',
                'instructions' => "1. Положите все ингредиенты в блендер.\n2. Взбейте до однородности.\n3. Подавайте сразу.",
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'easy',
                'calories' => 220,
                'proteins' => 8,
                'fats' => 5,
                'carbs' => 38,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'vegan', 'high-fiber'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Банан', 'amount' => 1, 'unit' => 'шт', 'category' => 'Фрукты'],
                    ['name' => 'Шпинат', 'amount' => 50, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Молоко миндальное', 'amount' => 200, 'unit' => 'мл', 'category' => 'Молочные'],
                    ['name' => 'Мёд', 'amount' => 10, 'unit' => 'г', 'category' => 'Прочее'],
                ],
            ],
            [
                'title' => 'Тефтели из индейки в томатном соусе',
                'slug' => 'tefteli-iz-indeyki',
                'description' => 'Нежные тефтели из индейки в домашнем томатном соусе.',
                'instructions' => "1. Смешайте фарш с яйцом и специями.\n2. Сформируйте тефтели.\n3. Обжарьте до корочки.\n4. Залейте томатным соусом.\n5. Тушите 20 минут.",
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 2,
                'difficulty' => 'medium',
                'calories' => 380,
                'proteins' => 32,
                'fats' => 15,
                'carbs' => 25,
                'category' => 'dinner',
                'dietary_tags' => ['high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Фарш из индейки', 'amount' => 300, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Яйцо куриное', 'amount' => 1, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Томатная паста', 'amount' => 50, 'unit' => 'г', 'category' => 'Соусы'],
                    ['name' => 'Лук репчатый', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Чеснок', 'amount' => 2, 'unit' => 'зубчика', 'category' => 'Овощи'],
                    ['name' => 'Зелень', 'amount' => 20, 'unit' => 'г', 'category' => 'Зелень'],
                ],
            ],
            [
                'title' => 'Кабачковые оладьи',
                'slug' => 'kabachkovye-oladi',
                'description' => 'Лёгкие оладьи из кабачков с зеленью.',
                'instructions' => "1. Натрите кабачок.\n2. Отожмите лишнюю влагу.\n3. Добавьте яйцо, муку, зелень.\n4. Обжарьте на сковороде.",
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'calories' => 180,
                'proteins' => 8,
                'fats' => 8,
                'carbs' => 20,
                'category' => 'dinner',
                'dietary_tags' => ['vegetarian', 'low-calorie'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Кабачок', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Яйцо куриное', 'amount' => 1, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Мука', 'amount' => 30, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Укроп', 'amount' => 15, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Масло растительное', 'amount' => 15, 'unit' => 'мл', 'category' => 'Масла'],
                ],
            ],
            [
                'title' => 'Куриный бульон с лапшой',
                'slug' => 'kuriniy-bulyon',
                'description' => 'Классический куриный суп с домашней лапшой.',
                'instructions' => "1. Сварите бульон из курицы.\n2. Добавьте овощи.\n3. Добавьте лапшу за 5 минут до готовности.\n4. Посыпьте зеленью.",
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 3,
                'difficulty' => 'medium',
                'calories' => 250,
                'proteins' => 20,
                'fats' => 8,
                'carbs' => 25,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein', 'comfort-food'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Курица (бедро)', 'amount' => 300, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Лапша яичная', 'amount' => 80, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Морковь', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Лук репчатый', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Картофель', 'amount' => 2, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Зелень', 'amount' => 20, 'unit' => 'г', 'category' => 'Зелень'],
                ],
            ],
            [
                'title' => 'Сырники из творога',
                'slug' => 'syrniki',
                'description' => 'Пышные сырники из творога со сметаной.',
                'instructions' => "1. Смешайте творог, яйцо, муку, сахар.\n2. Сформируйте сырники.\n3. Обжарьте на сковороде до золотистой корочки.\n4. Подавайте со сметаной.",
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'easy',
                'calories' => 350,
                'proteins' => 20,
                'fats' => 15,
                'carbs' => 35,
                'category' => 'breakfast',
                'dietary_tags' => ['vegetarian', 'high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Творог 9%', 'amount' => 250, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Яйцо куриное', 'amount' => 1, 'unit' => 'шт', 'category' => 'Яйца'],
                    ['name' => 'Мука', 'amount' => 40, 'unit' => 'г', 'category' => 'Крупы'],
                    ['name' => 'Сахар', 'amount' => 20, 'unit' => 'г', 'category' => 'Прочее'],
                    ['name' => 'Сметана 15%', 'amount' => 50, 'unit' => 'г', 'category' => 'Молочные'],
                ],
            ],
            [
                'title' => 'Салат Цезарь с курицей',
                'slug' => 'salat-tsezar',
                'description' => 'Классический салат Цезарь с куриной грудкой и пармезаном.',
                'instructions' => "1. Обжарьте курицу.\n2. Нарежьте салат романо.\n3. Приготовьте сухарики.\n4. Смешайте все ингредиенты.\n5. Заправьте соусом Цезарь.",
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 1,
                'difficulty' => 'medium',
                'calories' => 420,
                'proteins' => 35,
                'fats' => 25,
                'carbs' => 18,
                'category' => 'lunch',
                'dietary_tags' => ['high-protein'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Куриная грудка', 'amount' => 150, 'unit' => 'г', 'category' => 'Мясо'],
                    ['name' => 'Салат романо', 'amount' => 100, 'unit' => 'г', 'category' => 'Зелень'],
                    ['name' => 'Пармезан', 'amount' => 30, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Хлеб белый', 'amount' => 30, 'unit' => 'г', 'category' => 'Хлеб'],
                    ['name' => 'Соус Цезарь', 'amount' => 30, 'unit' => 'мл', 'category' => 'Соусы'],
                ],
            ],
            [
                'title' => 'Запечённые овощи с сыром',
                'slug' => 'zapechennye-ovoshchi',
                'description' => 'Ассорти овощей, запечённых с сыром моцарелла.',
                'instructions' => "1. Нарежьте овощи.\n2. Выложите в форму.\n3. Посыпьте сыром.\n4. Запекайте 25 минут при 180°C.",
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 2,
                'difficulty' => 'easy',
                'calories' => 220,
                'proteins' => 12,
                'fats' => 14,
                'carbs' => 15,
                'category' => 'dinner',
                'dietary_tags' => ['vegetarian', 'low-carb'],
                'is_published' => true,
                'ingredients' => [
                    ['name' => 'Кабачок', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Баклажан', 'amount' => 1, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Помидоры', 'amount' => 2, 'unit' => 'шт', 'category' => 'Овощи'],
                    ['name' => 'Моцарелла', 'amount' => 100, 'unit' => 'г', 'category' => 'Молочные'],
                    ['name' => 'Масло оливковое', 'amount' => 15, 'unit' => 'мл', 'category' => 'Масла'],
                    ['name' => 'Базилик', 'amount' => 10, 'unit' => 'г', 'category' => 'Зелень'],
                ],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['slug' => $recipeData['slug']],
                $recipeData
            );

            if ($recipe->wasRecentlyCreated) {
                foreach ($ingredients as $index => $ingredient) {
                    RecipeIngredient::create([
                        'recipe_id' => $recipe->id,
                        'ingredient_name' => $ingredient['name'],
                        'amount' => $ingredient['amount'],
                        'unit' => $ingredient['unit'],
                        'category' => $ingredient['category'] ?? 'Прочее',
                        'is_optional' => $ingredient['is_optional'] ?? false,
                        'order' => $index + 1,
                    ]);
                }
            }
        }
    }
}
